name: CI/CD Pipeline CITT

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

jobs:

  build-and-push:
    name: Build y Push a ECR
    runs-on: ubuntu-latest
    steps:

      - name: 1. Clonar el repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 3. Login a Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: 4. Build y Push back-ventas
        run: |
          docker build -f Dockerfile.backend \
            -t $ECR_REGISTRY/citt/back-ventas:${{ github.sha }} \
            -t $ECR_REGISTRY/citt/back-ventas:latest \
            './back-Ventas_SpringBoot/Springboot-API-REST'
          docker push $ECR_REGISTRY/citt/back-ventas:${{ github.sha }}
          docker push $ECR_REGISTRY/citt/back-ventas:latest

      - name: 5. Build y Push back-despachos
        run: |
          docker build -f Dockerfile.backend \
            -t $ECR_REGISTRY/citt/back-despachos:${{ github.sha }} \
            -t $ECR_REGISTRY/citt/back-despachos:latest \
            './back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO'
          docker push $ECR_REGISTRY/citt/back-despachos:${{ github.sha }}
          docker push $ECR_REGISTRY/citt/back-despachos:latest

      - name: 6. Build y Push front-despacho
        run: |
          docker build -f Dockerfile.frontend \
            -t $ECR_REGISTRY/citt/front-despacho:${{ github.sha }} \
            -t $ECR_REGISTRY/citt/front-despacho:latest \
            './front_despacho'
          docker push $ECR_REGISTRY/citt/front-despacho:${{ github.sha }}
          docker push $ECR_REGISTRY/citt/front-despacho:latest

  deploy:
    name: Deploy en EC2
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:

      - name: 7. Conectar a EC2 y desplegar
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            aws ecr get-login-password --region us-east-1 | \
              docker login --username AWS --password-stdin \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

            cd ~/proyecto

            docker compose -f docker-compose.prod.yml pull

            docker compose -f docker-compose.prod.yml up -d --force-recreate

            docker image prune -f

            echo "Despliegue completado"